### ISSUE TITLE
AttributeError: 'module' object has no attribute 'OPEN'

### ISSUE THREAD

**Issue by BackT0TheFuture** [GZHermit/darknet-visualization_script#1]
> E:\darknet-visualization_script>py app.py
> Traceback (most recent call last):
>   File "app.py", line 70, in OnChooseCfg
>     dlg = wx.FileDialog(self, "Choose Cfg file", self.dirname, "", "*.*", wx.OPE
> N)
> AttributeError: 'module' object has no attribute 'OPEN'
> Traceback (most recent call last):
>   File "app.py", line 70, in OnChooseCfg
>     dlg = wx.FileDialog(self, "Choose Cfg file", self.dirname, "", "*.*", wx.OPE
> N)
> AttributeError: 'module' object has no attribute 'OPEN'
> Traceback (most recent call last):
>   File "app.py", line 206, in OnOpen
>     dlg = wx.FileDialog(self, "Choose a file", self.dirname, "", "*.*", wx.OPEN)
>

**Comment by GZHermit** [comment]
It's impossible....I'm sure the wx.OPEN is existed in wx. So please check your wxPython version?My version is 3.0.2.0 and python version is python2.x

**Comment by johannsl** [comment]
It might be a problem with the wxPython version. I get the same error with wxPython 4.0.0b2. 

However, it seems to me that pip doesnt have the older versions of wxPython.

`pip2 install -I wxPython==3.0.2.0`
> Collecting wxPython==3.0.2.0
  Could not find a version that satisfies the requirement wxPython==3.0.2.0 (from versions: 4.0.0a1, 4.0.0a2, 4.0.0a3, 4.0.0b1, 4.0.0b2)
No matching distribution found for wxPython==3.0.2.0

Does anyone have any tips on how to set up the classic wx version with python?

**Comment by agirbau** [comment]
I changed everything to [wx.FD_OPEN](https://stackoverflow.com/questions/21373936/why-wxpython-carshes-while-using-id-open-wx-open) and it works properly (using wxPython 4.~). By the way, I thought this was to visualize the activations of the filters on inference, but at the end I realize that not even close ^^'. If you could write a couple of lines of the README that would help (as there's much noise in the internet on this topic). Thx!
